require 'pry'
require 'colorize'
require 'nokogiri'
require 'open-uri'
require 'json'
require 'pp'
require 'date'
#require 'httparty'
require_relative './cli.rb'
require_relative './zodiac.rb'
require_relative './scraper.rb'

