require 'pry'
require 'colorize'
require 'nokogiri'
require 'open-uri'
require 'json'
require 'pp'
#require 'httparty'
require_relative './zodiac.rb'
require_relative './zodiac2.rb'
require_relative './scraper2.rb'

